# To enable ssh & remote debugging on app service change the base image to the one below
# FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8-appservice
FROM mcr.microsoft.com/azure-functions/python:3.0-python3.8

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY requirements.txt /
RUN pip install -r /requirements.txt

RUN apt-get update && \
  apt-get -y upgrade &&\
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get install -y \
     git \
    gnuradio-dev \
    cmake \
    python3-pip 

#RUN echo "deb-src http://ppa.launchpad.net/gnuradio/gnuradio-releases-3.8/ubuntu bionic main" | tee /etc/apt/sources.list.d/gnuradio.list &&\
#    apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FC4DB82A1FA9AF51B5ADC3FB399F08D393C3C5C  && \
#    apt update && \
#    apt source -t bionic --build gnuradio

#RUN sed -i 's/buster\/updates/bullseye-security/g' /etc/apt/sources.list && \
#    sed -i 's/buster/bullseye/g' /etc/apt/sources.list && \
#    apt update && \
#    export DEBIAN_FRONTEND=noninteractive && \
#    apt full-upgrade -y

WORKDIR /src 
RUN git clone https://github.com/robotastic/azure-software-radio.git && \
    mkdir -p /src/build && \
    cd /src/azure-software-radio/ && \
    git checkout gr3.7 && \
    cd /src/azure-software-radio/gr-blob && \
    pip install -r python/requirements.txt && \
    cd /src/build && \
    cmake /src/azure-software-radio/gr-blob && \
    make install && \
    rm -rf /src/ 

RUN rm -rf /usr/lib/python2.7/dist-packages/enum*

COPY . /home/site/wwwroot

ENV LD_LIBRARY_PATH "/usr/lib" 
ENV PYTHONPATH "/usr/local/lib/python3/dist-packages:/usr/lib/python3/dist-packages:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages"
RUN ldconfig

WORKDIR /home/site/wwwroot/RadioStar