FROM ubuntu:21.04 AS base

# Install everything except cmake
RUN apt-get update && \
  apt-get -y upgrade &&\
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get install -y \
     git \
    cmake \
    python3-pip \
    software-properties-common \
    build-essential \
    libusb-dev libusb-1.0-0-dev \
    libsndfile1-dev \
    ca-certificates curl apt-transport-https lsb-release gnupg 

RUN add-apt-repository ppa:gnuradio/gnuradio-releases && \
    apt-get update && \
    apt-get install -y gnuradio \
        gnuradio-dev 


WORKDIR /src

RUN git clone https://github.com/microsoft/azure-software-radio.git

WORKDIR /src/azure-software-radio/gr-azure-software-radio

RUN pip install -r python/requirements.txt

WORKDIR /src/azure-software-radio/gr-azure-software-radio/build

RUN cmake .. && \
    make install

WORKDIR /src

RUN git clone https://github.com/librtlsdr/librtlsdr.git

WORKDIR /src/librtlsdr/build

RUN cmake ../ -DINSTALL_UDEV_RULES=ON && \
    make install && \
    ldconfig

WORKDIR /src

RUN git clone git://git.osmocom.org/gr-osmosdr

WORKDIR /src/gr-osmosdr/build

RUN cmake -DCMAKE_INSTALL_PREFIX=/usr ../ && \
    make install && \
    ldconfig

RUN apt install -y wget
RUN wget https://raw.githubusercontent.com/osmocom/rtl-sdr/master/rtl-sdr.rules -O /etc/udev/rules.d/20.rtlsdr.rules

WORKDIR /app
ENV LD_LIBRARY_PATH "${LD_LIBRARY_PATH}:/usr/lib/python3/dist-packages"
ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/python3/dist-packages:/usr/lib/python3/dist-packages"
RUN ldconfig