FROM ubuntu:21.04 AS base

# Install everything except cmake
RUN apt-get update && \
  apt-get -y upgrade &&\
  export DEBIAN_FRONTEND=noninteractive && \
  apt-get install -y \
     git \
    cmake \
    python3-pip \
    software-properties-common \
    build-essential \
    libusb-dev libusb-1.0-0-dev \
    libsndfile1-dev \
    ca-certificates curl apt-transport-https lsb-release gnupg 

RUN add-apt-repository ppa:gnuradio/gnuradio-releases && \
    apt-get update && \
    apt-get install -y gnuradio \
        gnuradio-dev 

WORKDIR /src

RUN curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null

RUN echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ focal main" | tee /etc/apt/sources.list.d/azure-cli.list

RUN apt-get update && \
    apt-get install azure-cli

RUN git clone https://github.com/microsoft/azure-software-radio.git

WORKDIR /src/azure-software-radio/gr-azure-software-radio

RUN pip install -r python/requirements.txt

WORKDIR /src/azure-software-radio/gr-azure-software-radio/build

RUN cmake .. && \
    make install

WORKDIR /src

RUN git clone https://github.com/librtlsdr/librtlsdr.git

WORKDIR /src/librtlsdr/build

RUN cmake ../ -DINSTALL_UDEV_RULES=ON && \
    make install && \
    ldconfig

WORKDIR /src

RUN git clone git://git.osmocom.org/gr-osmosdr

WORKDIR /src/gr-osmosdr/build

RUN cmake -DCMAKE_INSTALL_PREFIX=/usr ../ && \
    make install && \
    ldconfig

WORKDIR /app
ENV PYTHONPATH "${PYTHONPATH}:/usr/local/lib/python3/dist-packages"